name: Test Generate Docs

on:
  push:
    branches:
      - main

jobs:
  test-generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Docs Test
        run: |
          echo "Generating test documentation..."
          echo "## Test Documentation" > generated-docs.md
          echo "- Sample data point 1" >> generated-docs.md
          echo "- Sample data point 2" >> generated-docs.md
          cat generated-docs.md
